CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,1)
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 2
PRINT_FREQ: 10

DATASET:
  DATASET: suction
  ROOT: '/scratch/x956c659/data/richShot/suction_grasping/'
  TEST_SET: 'test-split.txt'
  TRAIN_SET: 'train-split.txt'
  NUM_CLASSES: 3
MODEL:
  NAME: ddrnet_23_slim
  NUM_OUTPUTS: 2
  PRETRAINED: "pretrained_models/DDRNet23s_imagenet.pth"
  ALIGN_CORNERS: true
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [1, 0.4]
TRAIN:
  IMAGE_SIZE:
  - 640
  - 480
  BATCH_SIZE_PER_GPU: 8
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 500
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.01
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  DOWNSAMPLERATE: 1
  IGNORE_LABEL: 255
  SCALE_FACTOR: 16
TEST:
  IMAGE_SIZE:
  - 640
  - 480
  BATCH_SIZE_PER_GPU: 4
  FLIP_TEST: false
  MULTI_SCALE: false
  SCALE_LIST: [1]
  #0.5,0.75,1.0,1.25,1.5,1.75
  # MODEL_FILE: "pretrained_models/best_val_smaller.pth"
  OUTPUT_INDEX: 1
